trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - kali

pr: none

pool:
  name: Ubuntu2004Pool

extends:
  template: ../devops-template.yaml
  parameters:
    project_dir: "kali"
    iso_url: "https://cdimage.kali.org/kali-2023.1/kali-linux-2023.1-installer-netinst-amd64.iso"
    iso_checksum: "sha256:344a8c948af62f7a288e3dc658291ec3d3cfcdbe5ad1e2f45334740bd6ff481d"
    image_name: "KaliLinux"
    image_version: "2023.1.0"
