trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - arch

pr: none

pool:
  name: Ubuntu2004Pool

extends:
  template: ../devops-template.yaml
  parameters:
    project_dir: "arch"
    iso_url: "http://ftp.fau.de/archlinux/iso/2022.06.01/archlinux-2022.06.01-x86_64.iso"
    iso_checksum: "sha256:6b3bfe8d4e0d0f82cc3322f9565e92b0c44f27105889a665a8626ce47fbf7ab8"
    image_name: "ArchLinux"
    image_version: "2022.06.01"
