trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - arch

pr: none

pool:
  name: Ubuntu2004Pool

extends:
  template: ../devops-template.yaml
  parameters:
    project_dir: "arch"
    iso_url: "http://ftp.fau.de/archlinux/iso/2022.01.01/archlinux-2022.01.01-x86_64.iso"
    iso_checksum: "sha1:efc9c33087e756ba1c7f326e67bfaa685eb51be3"
    image_name: "ArchLinux"
    image_version: "2022.01.01"