trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - arch

pr: none

pool:
  name: Ubuntu2004Pool

extends:
  template: ../devops-template.yaml
  parameters:
    project_dir: "arch"
    iso_url: "http://ftp.fau.de/archlinux/iso/2022.04.01/archlinux-2022.04.01-x86_64.iso"
    iso_checksum: "sha256:ec6aa0b0cc774415b2b28d110156326985bed5635ad7c9b16523fdad7da689a8"
    image_name: "ArchLinux"
    image_version: "2022.04.01"