trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - arch

pr: none

pool:
  name: Ubuntu2004Pool

extends:
  template: ../devops-template.yaml
  parameters:
    project_dir: "arch"
    iso_url: "http://ftp.fau.de/archlinux/iso/2021.10.01/archlinux-2021.10.01-x86_64.iso"
    iso_checksum: "sha1:77a20dcd9d838398cebb2c7c15f46946bdc3855e"
    image_name: "ArchLinux"
    image_version: "2021.10.01"