trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - arch

pr: none

pool:
  name: Ubuntu2004Pool

extends:
  template: ../devops-template.yaml
  parameters:
    project_dir: "arch"
    iso_url: "http://ftp.fau.de/archlinux/iso/2021.12.01/archlinux-2021.12.01-x86_64.iso"
    iso_checksum: "sha1:e303b93788220dbe8e0ba1804c90beebe432cf63"
    image_name: "ArchLinux"
    image_version: "2021.12.01"